---
- name: Deploy FirstDockViteApp
  hosts: application
  become: true

  tasks:

    - name: Update packages
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Install Docker
      ansible.builtin.dnf:
        name: docker
        state: present

    - name: Start Docker
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true

    - name: Verify Docker
      ansible.builtin.command:
        cmd: docker --version
      register: docker_version

    - name: Display Docker version
      ansible.builtin.debug:
        var: docker_version.stdout